
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: EDGE Innovation Labs
description: >- # this means to ignore newlines until "baseurl:"
  We are the digital transformation experts.
  We can help you in transforming your business.
subtitle: "A free HTML5 agency template"
url: "http://www.edgeinnovationlabs.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
